"""
    nparams, paramlist = jMtkFileCoreMetaDataQuery_tst_1100()

# Purpose:
Generate the output of `jMtkFileCoreMetaDataQuery` for testing purposes. Test 1100: For a MISR `GRP_ELLIPSOID_GM` file.

# Licensing:
* Mtk C Library: Copyright © 2005 California Institute of Technology,
    [Caltech license](https://github.com/nasa/MISR-Toolkit/blob/master/LICENSE).
* Julia wrapper: Copyright © 2023 Michel M. Verstraete,
    [MIT license](https://opensource.org/licenses/MIT).

# Versioning:
* Mtk C Library: Version 1.5.
* Julia wrapper: Version 0.1.0 (2023-02-15).

# Verification:
```idl
IDL> filename = root + 'MISR_AM1_GRP_ELLIPSOID_GM_P168_O068050_CF_F03_0024.hdf'
IDL> status = MTK_FILE_COREMETADATA_QUERY(filename, nparams, paramlist)
IDL> PRINT, nparams
          43
IDL> PRINT, paramlist
LOCALGRANULEID PRODUCTIONDATETIME LOCALVERSIONID PGEVERSION
    MEASUREDPARAMETERCONTAINER AUTOMATICQUALITYFLAGEXPLANATION AUTOMATICQUALITYFLAG
    QAPERCENTMISSINGDATA PARAMETERNAME ORBITCALCULATEDSPATIALDOMAINCONTAINER
    EQUATORCROSSINGDATE EQUATORCROSSINGTIME ORBITNUMBER EQUATORCROSSINGLONGITUDE
    VERSIONID SHORTNAME INPUTPOINTER GPOLYGONCONTAINER GRINGPOINTLONGITUDE
    GRINGPOINTLATITUDE GRINGPOINTSEQUENCENO EXCLUSIONGRINGFLAG RANGEENDINGDATE
    RANGEENDINGTIME RANGEBEGINNINGDATE RANGEBEGINNINGTIME ADDITIONALATTRIBUTESCONTAINER
    ADDITIONALATTRIBUTENAME PARAMETERVALUE ADDITIONALATTRIBUTESCONTAINER
    ADDITIONALATTRIBUTENAME PARAMETERVALUE ADDITIONALATTRIBUTESCONTAINER
    ADDITIONALATTRIBUTENAME PARAMETERVALUE ADDITIONALATTRIBUTESCONTAINER
    ADDITIONALATTRIBUTENAME PARAMETERVALUE ASSOCIATEDPLATFORMINSTRUMENTSENSORCONTAINER
    ASSOCIATEDSENSORSHORTNAME ASSOCIATEDPLATFORMSHORTNAME OPERATIONMODE
    ASSOCIATEDINSTRUMENTSHORTNAME
```

# Example:
```julia
julia> using JMtk15

julia> using Test

julia> include(JMtk15_test * "src/jMtkFileCoreMetaDataQuery_tst_1100.jl")
jMtkFileCoreMetaDataQuery_tst_1100

julia> nparams, paramlist = jMtkFileCoreMetaDataQuery_tst_1100();

julia> @test nparams == 43
Test Passed

julia> @test paramlist[4:8] == ["PGEVERSION", "MEASUREDPARAMETERCONTAINER",
    "AUTOMATICQUALITYFLAGEXPLANATION", "AUTOMATICQUALITYFLAG", "QAPERCENTMISSINGDATA"]
Test Passed

julia> @test paramlist[14:18] == ["EQUATORCROSSINGLONGITUDE", "VERSIONID", "SHORTNAME",
    "INPUTPOINTER", "GPOLYGONCONTAINER"]
Test Passed

julia> @test paramlist[37:40] == ["ADDITIONALATTRIBUTENAME", "PARAMETERVALUE",
    "ASSOCIATEDPLATFORMINSTRUMENTSENSORCONTAINER", "ASSOCIATEDSENSORSHORTNAME"]
Test Passed
```
"""
function jMtkFileCoreMetaDataQuery_tst_1100()
    filename = JMtk15_data * "MISR/MISR_AM1_GRP_ELLIPSOID_GM_P168_O068050_CF_F03_0024.hdf"
    nparams, paramlist = jMtkFileCoreMetaDataQuery(filename);
    return nparams, paramlist
end
